### ISSUE TITLE
Parsing issues with both Kape and Hoarder.

### ISSUE THREAD

**Issue by Comodooo** [DFIRKuiper/Kuiper#10]
Have been testing out the platform today with the .ova and it works great, no problem getting it up and running. The problem I'm having right now is that it seems to be some kind of import error when trying to just drag and drop the Kape zip for example. 

I tried the "KapeTriage" feature and exported it to a zip. When trying to import it directly I just get:

Error extract the zip content: 'utf8' codec can't decode byte 0x99 in position 81: invalid start byte

Any tips for how I can keep troubleshooting this?

**Comment by salehmuhaysin** [comment]
hi Comodooo,
this issue solved [here](https://github.com/DFIRKuiper/Kuiper/issues/8) 
Yes it seems like some issue with the ZipFile library decompressing the zip file,
this issue has been resolved on Github but the VM has not been changed
**Solution 1:**
copy the content of this page
> https://github.com/DFIRKuiper/Kuiper/blob/master/app/controllers/case_management.py

and replace it with the file 
>./app/controllers/case_management.py

**Solution 2:**
try cloning this project from the Github and run it again,

`$mkdir Kuiper-new`
`$cd Kuiper-new`
`$git clone https://github.com/DFIRKuiper/Kuiper.git`
`$cd Kuiper`
`$./kuiper_install.sh -run `
