### ISSUE TITLE
Kuiper modifies meaning of parsed data (quoting)

### ISSUE THREAD

**Issue by heck-gd** [DFIRKuiper/Kuiper#107]
Hello,

we have an issue with the following line:
https://github.com/DFIRKuiper/Kuiper/blob/dcb09077799da9ee9d063f87af8619b7683f0bad/kuiper/app/controllers/parser_management.py#L722

Assume you're doing forensics on PowerShell script executions and the following simplified script was executed and logged:
```powershell
$foo = "test"
Write-Host "$foo"
```

When Kuiper parses a Windows event containing the above code, it will turn it into:
```powershell
$foo = 'test'
Write-Host '$foo'
```

This is extremely problematic because it changes the meaning and essentially falsifies the collected data.

I'm wondering what the original reason for that `replace` was. We've changed it in our deployment a couple weeks ago and have not noticed any problem with Elasticsearch whatsoever.

And even if it does cause issues under very special circumstances, a generic replace on the entire data cannot be the solution.

**Comment by salehmuhaysin** [comment]
hello 
sorry, the problem not directly in the Elasticsearch, instead the rendering of the HTML of browse artifacts 
![image](https://github.com/DFIRKuiper/Kuiper/assets/34603893/3fd3d467-0f5d-43fc-8e26-111fcde776d3)

so when you click `equal` it will add only the first part before `"`
![image](https://github.com/DFIRKuiper/Kuiper/assets/34603893/dd55fef4-96b3-4167-909d-2836602aa3ed)


i will fix it

**Comment by salehmuhaysin** [comment]
issue fixed and updated to the source code, and will be added to version `2.3.5`
