### ISSUE TITLE
KAPE: Error extracting the archive content: compression type 9 (deflate64)

### ISSUE THREAD

**Issue by pisaura** [DFIRKuiper/Kuiper#109]
Hi together,

I've read the issues #12 and #33. I just want to find out if meanwhile there is a solution or a new workaround for this issue.
Re-compressing the data with another tool is not that much effort, but it would be really convenient using the automatic compression and naming capabilities of KAPE. 

**Describe the bug**
When uploading a ZIP file (Kuiper Version 2.3.4) generated by KAPE the following error occurs:
_Error extracting the archive content: compression type 9 (deflate64)_

**To Reproduce**
1. Generate ZIP file with KAPE (current version 1.3.0.2)
2. Upload ZIP file to Kuiper (version 2.3.4)
3. See error

**Expected behavior**
Extraction without errors without re-compressing the data with other tools as described in issue #33.
Also the current version didn't fix the issue as suggested in issue #12.

**Screenshots**
![Screenshot 2023-07-27 101218](https://github.com/DFIRKuiper/Kuiper/assets/50409310/51e08c5a-f0f4-4a9c-be4d-358e8752f87a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS (bionic)
 - Browser: Firefox 113.0.2 64-bit
 
**Additional context**
KAPE generates the ZIP file with compression method "enhanced deflated".
 ![enhanced_deflated](https://github.com/DFIRKuiper/Kuiper/assets/50409310/d1c38f16-3c0f-4e87-89cd-db256d69756f)
ZIP files with common compression "deflated" don't cause the error.

**Comment by salehmuhaysin** [comment]
hello 
i fixed the issue with the release `2.3.5`, now it will use 7z if ZipFile failed to open the file, I tested it now on KAPE results it should work fine.
