### ISSUE TITLE
Incorrect UserAssist Timestamps

### ISSUE THREAD

**Issue by dfirtracer** [DFIRKuiper/Kuiper#11]
**Describe the bug**
UserAssist Timestamps are not getting extracted from the artefact. When I click on the row, I could see the timestamp under a different field. Also are timestamps in UTC?

**To Reproduce**
Upload the NTUSER.DAT file

**Comment by DFIRKuiper** [comment]
hi
i will check the issue ASAP,
also Kuiper depends on the artifacts raw time zone, which is most likely is UTC+0
Windows store the times as UTC+0, when you want to present the data it change it depends on the system time zone
for example windows events stored UTC+0, but event viewer change it to the system timezone
