### ISSUE TITLE
Error uploading Kape ZIP file

### ISSUE THREAD

**Issue by jmmalcala** [DFIRKuiper/Kuiper#12]
Case Panel shows this error, after uploading a ZIP file from Kape: "**Error extract the zip content: compression type 9 (deflate64)"**

In this case, Kape was set up to collect artifacts and make a ZIP folder.  Does Kuiper work with vmdk cointainer inside ZIP file from Kape?

**Comment by jmmalcala** [comment]
I think the following code could solve the problem:
`from zipfile import ZipFile
import subprocess, sys

def Unzip(zipFile, destinationDirectory):
    try:
        with ZipFile(zipFile, 'r') as zipObj:
            # Extract all the contents of zip file in different directory
            zipObj.extractall(destinationDirectory)
    except:
        print("An exception occurred extracting with Python ZipFile library.")
        print("Attempting to extract using 7zip")
        subprocess.Popen(["7z", "e", f"{zipFile}", f"-o{destinationDirectory}", "-y"])`

**Comment by salehmuhaysin** [comment]
try the new release, multiple fixed issues added

**Comment by salehmuhaysin** [comment]
hello 
added the fix to the release to use the 7z if ZipFile failed, thank you
