### ISSUE TITLE
multi parsing not working

### ISSUE THREAD

**Issue by rav439** [DFIRKuiper/Kuiper#120]
**Describe the bug**
I have a 8 core VM with kuiper running. Only one artifact seems to be processing at a time. I think I used to see multiple "parsing" events.

**To Reproduce**
Add host
Add artifacts
parse all
hit files button
search for "parsing"
check how many parsing jobs there are

**Comment by salehmuhaysin** [comment]
Hello 
Kuiper perform the multiple processing in parallel on multiple machines, for single machine it only use single task.
for example, if you have 5 machines, it will do multiple processing utilizing 5 cores, if the system is less than 5 cores, the remaining machines will wait until a core become available.

Note: for multiple parsing at the same time in a single machine, check the premium version in https://cyberbomah.com.
