### ISSUE TITLE
RUnning Kuiper

### ISSUE THREAD

**Issue by faiisals** [DFIRKuiper/Kuiper#19]
Dears,

I'm facing issues when running the tool "./kuiper_install.sh -run", the following is displayed:

"Usage: celery worker [OPTIONS]

Try 'celery worker --help' for help.

Error: no such option: -A"

Kindly assist

**Comment by salehmuhaysin** [comment]
what is the version of celery?

**Comment by faiisals** [comment]
I'm getting the same error on both celery versions (5.0.0 and 5.0.2)

**Comment by salehmuhaysin** [comment]
there are multiple updates on celery 5.0 command line options, 
try using celery 4.3.0 it should work
