### ISSUE TITLE
Minor Installation Issue Nginx

### ISSUE THREAD

**Issue by Mikailo** [DFIRKuiper/Kuiper#22]
**Describe the bug**
During the installation after running 
` sudo ./kuiper_install.sh -install `

The installatio seemed to hang when installing Nginx. This is because it needed confirmation from the user to install the package but this wasn't printed to the terminal. Saw the prompt at the installation log.

**Comment by salehmuhaysin** [comment]
ok thanks
i think I should add ```-y```
