### ISSUE TITLE
Permisssions problems with the logs directory

### ISSUE THREAD

**Issue by pgarciabdfir** [DFIRKuiper/Kuiper#23]
**Describe the bug**
After the installation, in the first running of Kuiper, it raises a python error trace, regarding a lack of writting permissions in the logs directory

**To Reproduce**
1.- Install Kuiper from the scratch in a brand new machine 
2.- Run Kuiper
3.- Python error trace

**Expected behavior**
Don't get that error ;)

Fortunately It's easy to solve, I changed ownership of logs directory and all went fine. 

BTW, timeline is now working fine for me :)

**Comment by salehmuhaysin** [comment]
ok thanks
i think i should add change permissions when the installation done, or replace the installation logs path

**Comment by pgarciabdfir** [comment]
You are welcome
