### ISSUE TITLE
Kuiper Deb creation - riscv

### ISSUE THREAD

**Issue by kiranacs** [DFIRKuiper/Kuiper#24]
Hi, I was trying kuiper on riscv and able do native build without any issue. But In this sources Makefile don´t have install support. 
I have done as bellow:
*Git clone https://github.com/emqx/kuiper
*Cd kuiper
*make build_with_edgex

Note : In same build environment I can able run server. I copied binary to /usr/bin but still a issue in on board like missing conf files.
Can you help us to copy all relative file to respective path in board.

Is any layer support available for youcto.

Thanks,

**Comment by salehmuhaysin** [comment]
hi,
to install kuiper use `kuiper_install.sh`, do not use Makefile, we support Makefile
regarding the configuration file, what is the missed configuration file?, if you changed the directory, then ensure to modify the configuration files, all paths should use relative path of current directory `kuiper_install.sh` in
- configuration file `configuration.yml` https://github.com/DFIRKuiper/Kuiper/blob/master/configuration.yaml 
- nginx configuration `kuiper-nginx.conf` "https://github.com/DFIRKuiper/Kuiper/blob/master/kuiper-nginx.conf" (if you already installed kuiper, then modify the nginx configuration in "/etc/nginx/sites-available/kuiper-nginx.conf")

currently there is no plan to support `youcto`, maybe `dockers` in the future

**Comment by salehmuhaysin** [comment]
the issue will be closed
