### ISSUE TITLE
VirualMachine

### ISSUE THREAD

**Issue by Strannik74** [DFIRKuiper/Kuiper#27]
Hello!
i am very newbie
downloaded the kuiper virtual machine
I don't know how to connect to vmware from the main system now. Please tell me

**Comment by salehmuhaysin** [comment]
hi,

if you have access to the VMware application window, then you see the VM after importing it (its name depends on what you named it during the import)
if you dont have access to the VMware application, then you can access the VM through SSH using credentials (username: `kuiper`, password: `kuiper`) and the IP address you assigned to the machine (you should not the IP if you access the VM through VMware console)
