### ISSUE TITLE
Problem when I run Kuiper

### ISSUE THREAD

**Issue by minhnhat232k** [DFIRKuiper/Kuiper#28]
Hello, I'm newbie here. When I run $ ./kuiper_install.sh -run command. It's show me like this and I don't know how to enter the program interface. I run on 64-bit Ubuntu 18.04.1 LTS. Thanks for your attention.
![image](https://user-images.githubusercontent.com/56748091/124636961-574b5880-deb3-11eb-93b0-747d4e71cc92.png)
![image](https://user-images.githubusercontent.com/56748091/124637412-ece6e800-deb3-11eb-8275-4f80859ee0a5.png)

![image](https://user-images.githubusercontent.com/56748091/124639225-1c96ef80-deb6-11eb-95f1-9457f45f06b6.png)

**Comment by salehmuhaysin** [comment]
hi,
try to access it as ```https://localhost/```

**Comment by minhnhat232k** [comment]
Hello Saleh, 
I try https://localhost/6379 and here is the result and I don't know why.
![image](https://user-images.githubusercontent.com/56748091/124640975-5ff25d80-deb8-11eb-9d22-a3a19204e32e.png)

**Comment by salehmuhaysin** [comment]
the port 6379 is for celery not for the web 

try ```http://<machine-ip>/

also what is the result of ```netstat -nat | grep LIST```

**Comment by minhnhat232k** [comment]
I tried localhost:631 that is CUPS
![Capture](https://user-images.githubusercontent.com/56748091/124643892-d5136200-debb-11eb-9761-c612c50f0e4d.PNG)
localhost:5432 and localhost:27017 this is the result
![1](https://user-images.githubusercontent.com/56748091/124644189-2e7b9100-debc-11eb-9042-cf3e1e95ba2e.PNG)
Sorry to bother you.

**Comment by salehmuhaysin** [comment]
try change the path on kuiper nginx config.

https://github.com/DFIRKuiper/Kuiper/blob/master/kuiper-nginx.conf

to the correct path 

then run the following 

```
cp ./kuiper-nginx.conf /etc/nginx/sites-available/kuiper-nginx.conf
ln -s /etc/nginx/sites-available/kuiper-nginx.conf /etc/nginx/sites-enabled/
systemctl restart nginx
```

**Comment by minhnhat232k** [comment]
Thanks a lot !!!
