### ISSUE TITLE
Add horizontal scrolling to alerts overview table

### ISSUE THREAD

**Issue by 0x534a** [DFIRKuiper/Kuiper#30]
Hi!

please find the detailed description of the feature request below.

**Is your feature request related to a problem? Please describe.**
When adding rules with longer names, descriptions and queries, the alert overview table expands the wrapper `div` element with the id `alerts_table_wrapper`. Thus, the number of found alerts which is placed in the end of the table is not visible any more and there is no scroll bar in order to make them visible. The only option to see the number of found alerts is to expand the browser window.

**Describe the solution you'd like**
It would be prefereable to add the CSS option `overlow:auto` to the wrapper `div` with the ID `alerts_table_wrapper` in order to make horizontal scrolling possible. 

**Describe alternatives you've considered**
he only alternative option is to manually expand the browser window so that the table fits into the wrapper `div` element.

**Additional context**
No additional context.

Thank you very much for the effort that you put into Kuiper!

**Comment by salehmuhaysin** [comment]
thank you very much for the hint.
i added a hornizantal scroll bar to the alert table (will be updated in next release).

currently you can replace line 14 in page https://github.com/DFIRKuiper/Kuiper/blob/master/app/templates/case/alerts.html
```html
            <div class="box-body">
```
with 
```html
            <div class="box-body"  style="overflow:auto;" >
```
