### ISSUE TITLE
The letter 'Z' should be available as part of a case name.

### ISSUE THREAD

**Issue by blackdogbarking** [DFIRKuiper/Kuiper#31]
**Describe the bug**
When creating a case with a 'z' in the name, the 'z' is removed.

**To Reproduce**
1. go to the "Cases" on the Kuiper web UI.
2. click on the '+' sign.
3. create a case with a name containing the letter 'z'. For example, 'Zoo Zeeland'.
4. look at the name of the newly created case: 'ooeeland'.

**Expected behavior**
The letter 'z' should be available as part of a case name.

![Screenshot from 2021-08-30 13-32-11](https://user-images.githubusercontent.com/26471331/131332938-e33a2c85-9d77-4298-96cc-b9965a914dfa.png)

![Screenshot from 2021-08-30 13-32-35](https://user-images.githubusercontent.com/26471331/131332949-17d00d44-a852-4097-8c06-abaec199bcd8.png)

**Comment by maasdefence** [comment]
oh thats a bit wierd. we will test it and get back to you with a  fix..

**Comment by muteb** [comment]
we try to test it and get back to you.

**Comment by blackdogbarking** [comment]
I think this should be the Problem:
https://github.com/DFIRKuiper/Kuiper/blob/master/app/controllers/admin_management.py#L214
The Letter "z" is simply missing in `casename_accepted_char`.
Greetings.

**Comment by blackdogbarking** [comment]
I have opened a pull request for this.
https://github.com/DFIRKuiper/Kuiper/pull/34

**Comment by salehmuhaysin** [comment]
hi blackdogbarking,
i merged the pull request, 
thank you
