### ISSUE TITLE
How to uploaded "parsed" Hoarder zip?

### ISSUE THREAD

**Issue by gdms04** [DFIRKuiper/Kuiper#32]
After I used **hoarder --no_raw_files** and got the zip, I tried to upload to Kuiper. However, there is nothing happened after uploading and i tried to click process. However, its pops up error. May I know how to upload "parsed" result to Kuiper?

**Comment by maasdefence** [comment]
can you please print out the error and paste it here?

**Comment by muteb** [comment]
what is the error? can you paste it here.
