### ISSUE TITLE
Error uploading Kape ZIP file

### ISSUE THREAD

**Issue by nikitah4x** [DFIRKuiper/Kuiper#33]
I'm trying to upload Kape ZIP file, and I'm getting an error message:
Error extract the zip content: compression type 9 (deflate64)

I've installed the latest Kuiper version.

**Comment by salehmuhaysin** [comment]
hi nikitah4x, 
this is a common issue usually with Kuiper since it uses python2.7, some libraries does not support some features (such as deflate64)

try to decompress the file and compress it again, then try upload it to Kuiper

how much the file size?

**Comment by nikitah4x** [comment]
Hey,
I've decompressed it and compressed it manually, and now it got uploaded successfully.
