### ISSUE TITLE
"flask" and "celery" not working in Kuiper Docker installation

### ISSUE THREAD

**Issue by sinan-lab** [DFIRKuiper/Kuiper#39]
I'm trying to install Kuiper version 2.2.0. I didn't get any errors in the Docker installation. All items installed successfully. But when I run **"docker ps -a"** command, I found that **"kuiper_flask"** and **"kuiper_celery"** are not working. I ran **"docker-compose up -d"** again but it didn't fix it.

![2021-12-08_11-02-34](https://user-images.githubusercontent.com/57458584/145172828-51d75ef1-a07c-4e1a-97af-407d6cbc0e0c.png)

I also get the error **"502 Bad Gateway nginx/1.21.4"**. I think this is because of "flask" and "celery".

![image](https://user-images.githubusercontent.com/57458584/145175277-f3e8c9d9-5d46-4df1-9ab3-a332b8bf5a4e.png)

I tried opening Kuiper with Chrome(Version 96.0.4664.45 (Official Build) (64-bit)), Edge (Version 96.0.1054.43 (Official build) (64-bit)) and Firefox(Version 95.0 (64-bit)) .

The operating system I am trying to install Kuiper is **"Ubuntu 20.10"**

In addition; Cannot download because the download quota from "https://mega.nz/folder/i9UjyaQQ#DK97l_CzzhCa-y_E1dPULQ" is full. Can you offer a different option for download?

I look forward to your return as soon as possible. I wish you good work.

**Comment by sinan-lab** [comment]
Flask Log:

![image](https://user-images.githubusercontent.com/57458584/145196350-44a269ed-0daf-41c8-bfe2-ba1a4e6f7c94.png)

**Comment by salehmuhaysin** [comment]
you need to create "logs" folder on the Kuiper folder
