### ISSUE TITLE
Processing the machine image stuck on 99%

### ISSUE THREAD

**Issue by nikitah4x** [DFIRKuiper/Kuiper#44]
I've installed the latest version of Kuiper, and when I'm uploading a .zip output from Hoarder, the image process (parsers) is stuck at 99%.
![image](https://user-images.githubusercontent.com/58976181/151218898-922138b4-f25e-43cf-9521-5f3cb100aa09.png)

The screenshot is attached.
There are any logs or something that can help me with it??

I need help with understanding what the cause of it is.

**Comment by leba-gd** [comment]
Check what you see when you click on the "files" button. At the end it shows which files failed and why.

**Comment by nikitah4x** [comment]
> Check what you see when you click on the "files" button. At the end it shows which files failed and why.

Okay great, I can see that there are 3 files that are in error state.

Recyclebin parser - 'utf8' codec can't decode byte 0xd1 in position 1: invalid continuation byte - pushed rec. 0

**Comment by salehmuhaysin** [comment]
for troubleshooting a parser, i recommend to run it on your machine
- use the shell for celery docker `sudo docker-compose exec celery /bin/bash`
- go to `/kuiper/app/parsers/recyclebin_parser` or whatevery parser you want to troubleshoot.
- check the `Interface Function` in which file, then modify the interface file to call the interface function manully, the interface function accept two parameters (file , parser) - file is ithe file to parse, and parser is the parser name
- then start troubbleshooting the issue
