### ISSUE TITLE
Error: "docker-compose.yaml" is unsupported.

### ISSUE THREAD

**Issue by dr4lekhine** [DFIRKuiper/Kuiper#46]
Hi,

First of all, thank you for share your project.

I was trying to install this from first time, according to:
https://github.com/DFIRKuiper/Kuiper#Installation

However, Im facing the following issues:

root@kuiper-dfir:/opt/Kuiper# **docker-compose pull**
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

root@kuiper-dfir:/opt/Kuiper# **docker-compose up -d**
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

I don have enough experience with docker. Could you help me?:

**Ubuntu version:**

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Docker:**

Docker version 20.10.12, build e91ed57
docker-compose version 1.17.1, build unknown

Thanks in advance.

Regards.

**Comment by salehmuhaysin** [comment]
hi,
try to install the new version of docker compose 

https://docs.docker.com/compose/install/

**Comment by dr4lekhine** [comment]
Hi

After upgrade to "docker-compose version 1.29.2, build 5becea4c", it worked.

Thank you.


Regards.
