### ISSUE TITLE
Export Results Bug

### ISSUE THREAD

**Issue by Epod** [DFIRKuiper/Kuiper#50]
Unfortunately I can not provide screenshots. 

I am attempting to export results to a csv. In doing so, everything is exported, but the CSV only contains the date/timestamp columns. No other fields from the events are exported

**Comment by salehmuhaysin** [comment]
Hi,
It is not a bug, to export extra columns you need to add the column to the table so it will export it,
for example if you want the Hashes for amcache, search for data_type amcache, then add extra column 
![Selection_954](https://user-images.githubusercontent.com/34603893/154832852-0654da7f-7e80-40fc-9b89-78dc09c4528c.png)

it will export the new column hash

**Comment by Epod** [comment]
Adding them as a column appears to have no impact on the CSVs
