### ISSUE TITLE
export file

### ISSUE THREAD

**Issue by sinan-lab** [DFIRKuiper/Kuiper#58]
Hi, the data is not output in the export file.

![image](https://user-images.githubusercontent.com/57458584/169546516-a466002b-6949-435d-a69e-619603503770.png)

![image](https://user-images.githubusercontent.com/57458584/169546797-49f121b0-3f4f-4e0e-a85b-815ec33199d0.png)

**Comment by salehmuhaysin** [comment]
hi, the details field will not show on the exported data, it will export only the fixed fields "timestamp, data type, machine", you can add extra fields by clicked on add extra field button, these exrta fields will be exported on the csv output
![image](https://user-images.githubusercontent.com/34603893/169564074-532eb651-5041-4243-a7e6-9d42f4b550b7.png)
