### ISSUE TITLE
Ability to Edit Machine info

### ISSUE THREAD

**Issue by rvital-f** [DFIRKuiper/Kuiper#63]
Hello,

Would it be possible to add the ability to edit Machine Info?

Or maybe I cant seem to find it. After I upload a triage package, I'd like to rename the Machine name and IP address within Kuiper.

Thanks

**Comment by salehmuhaysin** [comment]
hi 
it is not possible now to edit the machine information, you can add new machine (and specify the name and ip) then upload the triage package as zip file, but you cannot modify it

**Comment by rvital-f** [comment]
Ok thanks for the confirmation, may I make a feature request to add this?

**Comment by salehmuhaysin** [comment]
hi, 
yes
