### ISSUE TITLE
list docker-compose version

### ISSUE THREAD

**Issue by rvital-f** [DFIRKuiper/Kuiper#72]
Hello,

Install guide is missing commands to install docker-compose, also recommended version for docker-compose as well.

seems to be the most difficult part of the install process is getting the right docker version.

if you install docker-compose through apt-get it says its an incompatible version with the yaml.

please list the preferred docker-compose version(s)

Thanks!

**Comment by salehmuhaysin** [comment]
Hi, 
thank you for your notice 
the version im using 
- Docker: Docker version 20.10.17
- Docker-Compose: docker-compose version 1.29.2

I also just added the installation steps to the readme in the requirements section

**Comment by rvital-f** [comment]
perfect, thanks!!
