### ISSUE TITLE
v2.3.3 Issue: kuiper_flask is constantly restarting and does not start on 

### ISSUE THREAD

**Issue by HungryEmperor** [DFIRKuiper/Kuiper#81]
# Description

Issue: kuiper_flask is constantly restarting and does not start.
kuiper_flask     /bin/sh -c cron &&         Restarting                          
                 gunicor ...          

Tested:
Docker version 20.10.17, build 100c701
docker-compose version 1.29.2, build 5becea4c
Ubuntu 22.04 LTS and Ubuntu 18.01 LTS

# To Reproduce
I followed installation via method provided. Also manually installed Docker version 20.10.17, build 100c701 for testing. This is done on fresh images of Ubuntu. Tested on both Ubuntu 22.04 LTS and Ubuntu 18.01 LTS.

-Install Docker
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg lsb-release
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo docker -v

-Install Docker Compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo docker-compose -v

-Install Kuiper
sysctl -w vm.max_map_count=262144
git clone https://github.com/DFIRKuiper/Kuiper.git
cd Kuiper
docker-compose pull
docker-compose up -d

# Error Log
docker-compose logs -f --tail=100 flask

Error:
flask_1    | Error: class uri 'gevent' invalid or not found: 
flask_1    | 
flask_1    | [Traceback (most recent call last):
flask_1    |   File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 142, in load_class
flask_1    |     mod = import_module('.'.join(components))
flask_1    |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
flask_1    |     __import__(name)
flask_1    |   File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 20, in <module>
flask_1    |     import gevent
flask_1    |   File "/usr/local/lib/python2.7/site-packages/gevent/__init__.py", line 87, in <module>
flask_1    |     from gevent._hub_local import get_hub
flask_1    |   File "/usr/local/lib/python2.7/site-packages/gevent/_hub_local.py", line 101, in <module>
flask_1    |     import_c_accel(globals(), 'gevent.__hub_local')
flask_1    |   File "/usr/local/lib/python2.7/site-packages/gevent/_util.py", line 105, in import_c_accel
flask_1    |     mod = importlib.import_module(cname)
flask_1    |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
flask_1    |     __import__(name)
flask_1    |   File "src/gevent/__greenlet_primitives.pxd", line 12, in init gevent.__hub_local
flask_1    | ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 128 from C header, got 40 from PyObject
flask_1    | ]
flask_1    | 

# Further Information:

Confirmed gevent is installed as part of the Kuiper.ps1. 

''Successfully installed Evtx-0.4.0 Flask-0.10.1 Flask-Celery-Helper-1.1.0 Jinja2-2.11.3 MarkupSafe-1.1.1 PyYAML-5.1.2 Pygments-2.5.2 Shapely-1.6.4.post2 Unidecode-1.0.23 Werkzeug-0.10.1 alabaster-0.7.12 amqp-2.6.1 anyjson-0.3.3 atomicwrites-1.4.1 attrs-21.4.0 babel-2.9.1 backports.functools-lru-cache-1.6.4 billiard-3.6.4.0 booleano-1.1a2 celery-4.3.0 certifi-2021.10.8 chardet-3.0.4 coverage-5.5 defusedxml-0.7.1 docutils-0.17.1 elasticsearch-7.6.0 enum34-1.1.10 et-xmlfile-1.0.1 funcsigs-1.0.2 **gevent-1.4.0** greenlet-2.0.0 gunicorn-19.4.5 hexdump-3.3 idna-2.8 imagesize-1.4.1 itsdangerous-1.1.0 jdcal-1.4.1 kombu-4.6.11 libesedb-python-20210424 libscca-python-20181227 lxml-3.5.0 more-itertools-5.0.0 olefile-0.46 openpyxl-2.6.4 packaging-20.9 pluggy-0.13.1 protobuf-3.10.0 psutil-5.7.0 py-1.11.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pymongo-2.8 pyparsing-2.4.7 pytest-4.6.6 pytest-cov-2.12.1 python-dateutil-2.8.0 python-evtx-0.6.1 python-ldap-3.3.1 python-registry-1.0.4 pytz-2022.6 redis-3.3.11 registry-0.4.2 requests-2.21.0 six-1.10.0 snowballstemmer-2.2.0 sphinx-1.8.6 sphinx-rtd-theme-0.4.3 sphinxcontrib-websupport-1.1.2 toml-0.10.2 unicodecsv-0.14.1 urllib3-1.24.1 vine-1.3.0 wcwidth-0.2.5 webapp2-2.5.2 winjob-0.0.0 xmltodict-0.12.0''

**Comment by alexshively** [comment]
I'm not sure what the specific version is, however, if you go to: kuiper/requirements_2.7.txt
Change `gevent==1.4.0` to just `gevent` and rebuild, should be good

**Comment by HungryEmperor** [comment]
@alexshively Perfect fixed! Many thanks!
