### ISSUE TITLE
Worker exited prematurely: signal 9 (SIGKILL) Job: 3.

### ISSUE THREAD

**Issue by nikitah4x** [DFIRKuiper/Kuiper#90]
**Describe the bug**
Worker exited prematurely: signal 9 (SIGKILL) Job: 3.

**To Reproduce**
1. Take KAPE Output
2. Upload it to Kuiper

**Expected behavior**
All Files are without Error

**Screenshots**
![image](https://user-images.githubusercontent.com/58976181/220888384-5ff4a8bd-f6c5-40c9-b15d-f0817197a7b1.png)

**Desktop (please complete the following information):**
 - OS: Windows Server

**Comment by salehmuhaysin** [comment]
can you check the file log 
/kuiper/files/logs/Kuiper.log

some assumption in might be becouse of lack of avaliable memory space
