### ISSUE TITLE
ZIP files not uploading

### ISSUE THREAD

**Issue by nyrm-f** [DFIRKuiper/Kuiper#93]
ZIP files are not uploaded

1. Make new case
2. Upload zip file

I check the file system in kuiper/kuiper/files/<case_name>/<triage_name>/ 

and the folder will be empty after the upload bar is green.
<img width="431" alt="Screenshot 2023-03-21 at 3 24 14 PM" src="https://user-images.githubusercontent.com/110699325/226755575-8e05d57b-fb8e-4263-be29-28874513e5ef.png">

I'm using a fresh install of kuiper. File uploading is broken somehow

**Comment by salehmuhaysin** [comment]
hello 
try again to upload it, and get the output of the file "kuiper/files/logs/Kuiper.log"
also try to unzip the file then zip it again, some time there is problem with the compression
